# Generated by Django 5.1.4 on 2025-01-03 12:14

import django.utils.timezone
import user_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.IntegerField(choices=[(1, 'admin of the system'), (2, 'shop owner'), (3, 'staff in the branch')], default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('profile_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=user_management.models.upload_path)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_userdata_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_userdata_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
