# Generated by Django 5.1.4 on 2025-01-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
