# Generated by Django 5.1.4 on 2025-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_userdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
