# Generated by Django 5.1.4 on 2025-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
